### ISSUE TITLE
Create Netlify Test Environment with Continuous Integration

### ISSUE THREAD

**Issue by Underwaterr** [SEI-39/developerverse#5]
Using GitHub actions, the front-end should be deployed to the Netlify test environment automatically every time someone merges a branch into `main`.

**Comment by LexLeach** [comment]
Netlify sent a request that needs to be approved

**Comment by Underwaterr** [comment]
@LexLeach can you give me more details? Is this something I need to do in GitHub? Something that we'll have to wait on?

**Comment by LexLeach** [comment]
Netlify sent the request to the github repo author I believe. Seeing as I didn't get the approval request I would assume it was sent to you.

**Comment by Underwaterr** [comment]
@LexLeach done!

**Comment by Underwaterr** [comment]
@LexLeach is there more work to be done? Should this ticket be closed?

**Comment by LexLeach** [comment]
Still working on it, it is not finished.

**Comment by LexLeach** [comment]
Netlify is up an running, live@: https://developerverse.netlify.app/
