### ISSUE TITLE
Create FONTS.md and STYLEGUIDE.md

### ISSUE THREAD

**Issue by cblender** [SEI-39/developerverse#85]
FONTS.md will contain the information for the T26.Carbon font we are using for the title, headers, and other decorative elements.  This includes the import link for adding the font to the project, as well as the specific CSS code for implementing the font in a stylesheet.

STYLEGUIDE.md will contain brief descriptions of important elements of DeveloperVerse's style.  It should be easy to read and remember, and will ensure that the styling of the site is consistent.

**Comment by iandemed** [comment]
Chris completed both of these tasks.
